## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
notifications:
  email: false
branches:
  only:
    - master

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("BooSTjl"); Pkg.test("BooSTjl"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter.jl")'
  - julia -e 'cd(Pkg.dir("BooSTjl")); include(joinpath("docs", "make.jl"))'
